/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package anatri.view;
import anatri.model.Operater;
import anatri.utility.Pomocno;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author TryGor
 */
public class Autorizacija extends javax.swing.JFrame {

    private int brojPokusaja;
    private anatri.controller.Autorizacija autorizacija;
    /**
     * Creates new form Autorizacija
     */
    public Autorizacija() {
        initComponents();
        setLocationRelativeTo(null);
        
        SimpleDateFormat df = new SimpleDateFormat(Pomocno.FORMAT_DATUM);
        datum.setText(df.format(new Date()));
        
        brojPokusaja=0;
        autorizacija = new anatri.controller.Autorizacija();
        SatNit t = new SatNit(datum);
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        korisnik = new javax.swing.JTextField();
        lozinka = new javax.swing.JPasswordField();
        autoriziraj = new javax.swing.JButton();
        poruka = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        datum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anatri Rent A Car v2.1 Log in");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("KORISNIČKO IME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("LOZINKA");

        korisnik.setText("Admin");
        korisnik.setPreferredSize(new java.awt.Dimension(6, 30));
        korisnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                korisnikKeyPressed(evt);
            }
        });

        lozinka.setText("Goc1977");
        lozinka.setPreferredSize(new java.awt.Dimension(6, 30));
        lozinka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lozinkaKeyPressed(evt);
            }
        });

        autoriziraj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        autoriziraj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/login-key6.png"))); // NOI18N
        autoriziraj.setText("ULOGIRAJTE SE");
        autoriziraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizirajActionPerformed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(0, 204, 204));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setToolTipText("Anatri");
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.add(datum);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Rent a car-200px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(poruka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(32, 32, 32)
                                    .addComponent(korisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(autoriziraj, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(lozinka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(poruka, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoriziraj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autorizirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizirajActionPerformed
        
        if(brojPokusaja==3){
            autoriziraj.requestFocus();
            dispose();
            
            new Greska().setVisible(true);
            return;
       
        }
        brojPokusaja++;
        poruka.setText("");
        if(korisnik.getText().trim().length()==0){
           poruka.setText("Korisničko ime je obavezno");
           korisnik.requestFocus();
           return;
       } 
        if(new String(lozinka.getPassword()).
                trim().length()==0){
            poruka.setText("Lozinka je obavezna");
            lozinka.requestFocus();
            return;
        }
        
        Operater o = autorizacija.autoriziraj(korisnik.getText().trim(), new String(lozinka.getPassword()).trim());
        
        if(o==null){
        poruka.setText("Kombinacija netočna");
        return;
        }
        
        //poziv forme izbornika
         new Izbornik().setVisible(true);
         dispose();
    }//GEN-LAST:event_autorizirajActionPerformed

    private void korisnikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_korisnikKeyPressed
        if(evt.getKeyCode()==
                KeyEvent.VK_ENTER){
            autorizirajActionPerformed(null);
        }
    }//GEN-LAST:event_korisnikKeyPressed

    private void lozinkaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lozinkaKeyPressed
        if(evt.getKeyCode()==
                KeyEvent.VK_ENTER){
            autorizirajActionPerformed(null);
        }
    }//GEN-LAST:event_lozinkaKeyPressed
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/slike/logo_mali.png/")));
    }
 
 


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoriziraj;
    private javax.swing.JLabel datum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField korisnik;
    private javax.swing.JPasswordField lozinka;
    private javax.swing.JLabel poruka;
    // End of variables declaration//GEN-END:variables
}
