/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package anatri.view;

import anatri.utility.Pomocno;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author TryGor
 */
public class Izbornik extends javax.swing.JFrame {
    private Vozila v;
    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        
        setLocationRelativeTo(null);
                
        setTitle("ANATRI Rent A Car v2.1 GLAVNI IZBORNIK " + 
               Pomocno.getOperater().getImePrezime());
        
        SimpleDateFormat df = new SimpleDateFormat(Pomocno.FORMAT_DATUM);
        datum.setText(df.format(new Date()));
        
        SatNit t = new SatNit(datum);
        t.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        datum = new javax.swing.JLabel();
        operateri = new javax.swing.JButton();
        vozila = new javax.swing.JButton();
        grupe = new javax.swing.JButton();
        klijenti = new javax.swing.JButton();
        djelatnici = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rezervacije = new javax.swing.JButton();
        oprema = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        izlaz = new javax.swing.JMenuItem();
        promjenaKorisnika = new javax.swing.JMenuItem();
        pomoc = new javax.swing.JMenu();
        oNama = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jToolBar1.setBackground(new java.awt.Color(0, 204, 204));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        datum.setMaximumSize(new java.awt.Dimension(200, 40));
        jToolBar1.add(datum);

        operateri.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        operateri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Operteri.png"))); // NOI18N
        operateri.setText("Operateri");
        operateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operateriActionPerformed(evt);
            }
        });

        vozila.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        vozila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/camaro-icon.png"))); // NOI18N
        vozila.setText("Vozila");
        vozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vozilaActionPerformed(evt);
            }
        });

        grupe.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        grupe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/grupe.png"))); // NOI18N
        grupe.setText("Grupe");
        grupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupeActionPerformed(evt);
            }
        });

        klijenti.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        klijenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/klijenti.png"))); // NOI18N
        klijenti.setText("Klijenti");
        klijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klijentiActionPerformed(evt);
            }
        });

        djelatnici.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        djelatnici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Workers.png"))); // NOI18N
        djelatnici.setText("Djelatnici");
        djelatnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djelatniciActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Osijek-1.png"))); // NOI18N

        rezervacije.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        rezervacije.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/rezervacija.png"))); // NOI18N
        rezervacije.setText("Rezervacije");
        rezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezervacijeActionPerformed(evt);
            }
        });

        oprema.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        oprema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Equipment.png"))); // NOI18N
        oprema.setText("Oprema");
        oprema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opremaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Rent a car-200px.png"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Anatri");

        izlaz.setText("Izlaz");
        izlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlazActionPerformed(evt);
            }
        });
        jMenu1.add(izlaz);

        promjenaKorisnika.setText("Promijeni korisnika");
        promjenaKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjenaKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(promjenaKorisnika);

        jMenuBar1.add(jMenu1);

        pomoc.setText("Pomoć");
        pomoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomocActionPerformed(evt);
            }
        });

        oNama.setText("O Nama");
        oNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oNamaActionPerformed(evt);
            }
        });
        pomoc.add(oNama);

        jMenuBar1.add(pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(djelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operateri, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(vozila, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oprema, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(klijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grupe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(klijenti)
                                .addGap(33, 33, 33)
                                .addComponent(grupe)
                                .addGap(38, 38, 38)
                                .addComponent(oprema))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(operateri)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(djelatnici)
                                    .addComponent(vozila, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(rezervacije)))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("ANATRI APP");
        getAccessibleContext().setAccessibleDescription("RENT A CAR OSIJEK");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlazActionPerformed
       dispose();
    }//GEN-LAST:event_izlazActionPerformed

    private void pomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomocActionPerformed
        System.out.println("Krećem");
        new Onama().setVisible(true);
    }//GEN-LAST:event_pomocActionPerformed

    private void oNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oNamaActionPerformed
       new Onama().setVisible(true);
       
    }//GEN-LAST:event_oNamaActionPerformed

    private void operateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operateriActionPerformed
        new Operateri().setVisible(true);
       
    }//GEN-LAST:event_operateriActionPerformed

    private void vozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vozilaActionPerformed
      new Vozila().setVisible(true);
      
    }//GEN-LAST:event_vozilaActionPerformed

    private void grupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupeActionPerformed
       new Grupe().setVisible(true);
       
    }//GEN-LAST:event_grupeActionPerformed

    private void klijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klijentiActionPerformed
        new Klijenti().setVisible(true);
        
    }//GEN-LAST:event_klijentiActionPerformed

    private void djelatniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djelatniciActionPerformed
        new Djelatnici().setVisible(true);
        
    }//GEN-LAST:event_djelatniciActionPerformed

    private void rezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezervacijeActionPerformed
        new Rezervacije().setVisible(true);
       
    }//GEN-LAST:event_rezervacijeActionPerformed

    private void opremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opremaActionPerformed
        new Opreme().setVisible(true);
        
    }//GEN-LAST:event_opremaActionPerformed

    private void promjenaKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjenaKorisnikaActionPerformed
        new Autorizacija().setVisible(true);
        dispose();
    }//GEN-LAST:event_promjenaKorisnikaActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datum;
    private javax.swing.JButton djelatnici;
    private javax.swing.JButton grupe;
    private javax.swing.JMenuItem izlaz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton klijenti;
    private javax.swing.JMenuItem oNama;
    private javax.swing.JButton operateri;
    private javax.swing.JButton oprema;
    private javax.swing.JMenu pomoc;
    private javax.swing.JMenuItem promjenaKorisnika;
    private javax.swing.JButton rezervacije;
    private javax.swing.JButton vozila;
    // End of variables declaration//GEN-END:variables
}
